DROP TABLE customers IF EXISTS;

CREATE TABLE TRANSACTIONS (
    CLIENT_TYPE VARCHAR(255),
    CLIENT_NUMBER VARCHAR(255),
    ACCOUNT_NUMBER VARCHAR(255),
    SUBACCOUNT_NUMBER VARCHAR(255),
    EXCHANGE_CODE VARCHAR(255),
    PRODUCT_GROUP_CODE VARCHAR(255),
    SYMBOL VARCHAR(255),
    EXPIRATION_DATE VARCHAR(255),
    QUANTITY_LONG INTEGER,
    QUANTITY_SHORT INTEGER
);